### ISSUE TITLE
the macros O_RDONLY, O_WRONLY, O_RDWR, O_NONBLOCK must be defined if no defined previously

### ISSUE THREAD

**Issue by gmuro** [ciaa/Firmware#179]
the macros O_RDONLY, O_WRONLY, O_RDWR, O_NONBLOCK must be defined if no defined previously. And include ciaaPOSIX_stdio.h after stdio.h (if necessary include stdio.h :)

**Comment by mcerdeiro** [comment]
is possible to use the same values as linux?

**Comment by gmuro** [comment]
yes, temporary solution...

**Comment by evolentini** [comment]
We need to include stdio.h because emulated version of driver needs access to the host functions open, read, write and close. We can't change the macros to avoid a new definition if it is previously defined. It isn't a solution because the stdio.h is not included in all files of project  and as result we'd have a macro with a value in ciaaDriversSerial.c and a different value in Blinking.c.
The solution currently implemented is using the same value of unix and include the host system includes before of ciaa includes. By this way if exist an redefinition of macro, the compiler'll generate a warning. The problem is that O_RDONLY is a macro and the warning is generated even if value is the same but it is written in different form, for example 1 and 0x0001
I believe that the only complete solution for this problem is change  macro's name to CIAA_O_RDONLY, but I don't like it.
